os: Visual Studio 2015

platform:
  - x64

skip_tags: true

build: off

environment:
  nodejs_version: "8.9.4"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

test_script:
  - yarn run ci

for:
  - configuration: Test
  - configuration: Release
    branches:
      only:
        - /^release\/.+/
    deploy_script:
      - yarn run publish
