os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "8.9.0"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force

build: off

test_script:
  - yarn run lint
  - yarn run test
